name: Compile the project

on: 
  push
  # pull_request:
  #   branches:
  #     - main

jobs:
  kernel-compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Try the compilation cache for riscv toolchain
        id: cache-riscv-gcc
        uses: actions/cache@v4
        with: 
          path: |
            /opt/riscv
            /usr/local/share/uriscv
          key: ${{ runner.os }}-riscv-gcc-opt

      - name: Clone the riscv toolchain
        if: steps.cache-riscv-gcc.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: riscv/riscv-gnu-toolchain
          path: riscv-gcc-repo

      - name: Install needed packages
        run: sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev

      - name: Build the toolchain
        if: steps.cache-riscv-gcc.outputs.cache-hit != 'true'
        run: cd riscv-gcc-repo && ./configure --prefix=/opt/riscv --with-arch=rv32gc --with-abi=ilp32d && sudo make -j $(nproc) linux

      # - name: Add riscv-gcc to PATH
      #   run: export PATH=$PATH:/opt/riscv
      #
      # - name: Checkout the kernel repo
      #   uses: actions/checkout@v4
      #   with:
      #     path: kebab-os
      #
      # - name: Build the kernel
      #   run: cd kebab-os && make
