name: Compile the project

on: 
  push
  # pull_request:
  #   branches:
  #     - main

jobs:
  copilation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the riscv-gcc compiler
        uses: actions/checkout@v4
        with:
          repository: riscv/riscv-gnu-toolchain
          path: riscv-gcc-repo

      - name: Install needed packages
        run: sudo apt-get install autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build git cmake libglib2.0-dev

      - name: Build the toolchain
        run: cd riscv-gcc-repo && ./configure --prefix=$GITHUB_WORKSPACE/riscv-gcc --with-arch=rv32gc --with-abi=ilp32d && sudo make -j $(nproc) linux
